services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: auto_cold_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - auto_cold_network
    depends_on:
      db:
        condition: service_healthy

  webserver:
    image: nginx:alpine
    container_name: auto_cold_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auto_cold_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: auto_cold_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auto_cold
      MYSQL_USER: auto_cold_user
      MYSQL_PASSWORD: "Ac#9vX2$kL8mP@4wTy7!Rz"
      MYSQL_ROOT_PASSWORD: "Rt#8mQ4$uW1pZ@9eKx3!Vb"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - auto_cold_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRt#8mQ4$uW1pZ@9eKx3!Vb"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: auto_cold_phpmyadmin
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "Rt#8mQ4$uW1pZ@9eKx3!Vb"
    networks:
      - auto_cold_network
    depends_on:
      - db

networks:
  auto_cold_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
